# Site settings
title: Akashic Records For JEE
description: >-
  Open source JEE knowledge for everyone. Free. Forever.
baseurl: ""
url: "https://akashicrecords4jee.github.io"
repository: akashicrecords4jee/akashicrecords4jee.github.io

# Theme settings
theme: just-the-docs
remote_theme: just-the-docs/just-the-docs
color_scheme: ar4j
search_enabled: true
search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

# Aux links for upper right navigation
aux_links:
  "View on GitHub":
    - "//github.com/akashicrecords4jee/akashicrecords4jee.github.io"
aux_links_new_tab: true

# Footer content
footer_content: "Copyright &copy; 2025 Akashic Records 4 JEE. Distributed under MIT license."

# Collections for different subjects
collections:
  preface:
    output: true
    permalink: /preface/:path/
  physics:
    output: true
    permalink: /physics/:path/
  chemistry:
    output: true
    permalink: /chemistry/:path/
  maths:
    output: true
    permalink: /maths/:path/

# Configure collections for navigation
just_the_docs:
  collections:
    preface:
      name: Preface
      nav_fold: true
    physics:
      name: Physics
      nav_fold: true
    chemistry:
      name: Chemistry
      nav_fold: true
    maths:
      name: Maths
      nav_fold: true

# Use Kramdown as the markdown processor
markdown: kramdown

# Tell Jekyll to use MathJax for math rendering
math: mathjax

# Configure Kramdown to pass through math delimiters
kramdown:
  math_engine: mathjax
  math_engine_opts:
    inline_math_delims: ['\\(', '\\)']
    display_math_delims: ["$$", "$$"]

# Exclude files from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
  - CONTRIBUTING.md
  - LICENSE.md
